CREATE DATABASE IF NOT EXISTS CUSTOMERS;
USE CUSTOMERS;
DROP TABLE IF EXISTS CUSTOMERS;
CREATE TABLE CUSTOMERS
(
    ID INT NOT NULL auto_increment,
    NAME varchar(20) NOT NULL,
    AGE INT NOT NULL,
    ADDRESS varchar(25),
    SALARY DECIMAL(18,2),
    PRIMARY KEY(ID)
);
INSERT INTO CUSTOMERS(ID, NAME, AGE, ADDRESS, SALARY)
VALUES(1, 'AKHIL', 32, 'HYDERABAD', 2000);
INSERT INTO CUSTOMERS(ID, NAME, AGE, ADDRESS, SALARY)
VALUES(2, 'KUMAR', 22, 'GOA', 3000);
INSERT INTO CUSTOMERS(ID, NAME, AGE, ADDRESS, SALARY)
VALUES(5, 'MAHESH', 56, 'MILAN', 30000); 



   