CREATE DATABASE IF NOT EXISTS CUSTOMERS;
USE CUSTOMERS;
DROP TABLE IF EXISTS CUSTOMERS;
CREATE TABLE CUSTOMERS
(
    ID INT NOT NULL auto_increment,
    NAME varchar(20) NOT NULL,
    AGE INT NOT NULL,
    ADDRESS varchar(25),
    SALARY DECIMAL(18,2),
    PRIMARY KEY(ID)
);
INSERT INTO CUSTOMERS(ID, NAME, AGE, ADDRESS, SALARY)
VALUES(1, 'MINI', 32, 'AGRA', 2000);
INSERT INTO CUSTOMERS(ID, NAME, AGE, ADDRESS, SALARY)
VALUES(2, 'JAIN', 22, 'NOIDA', 3000);
INSERT INTO CUSTOMERS(ID, NAME, AGE, ADDRESS, SALARY)
VALUES(5, 'GIRISH', 56, 'SATISH', 30000); 